### ISSUE TITLE
ConcurrentModificationException przy części operacji na listach tokenów armii

### ISSUE THREAD

**Issue by DcortezMeleth** [DcortezMeleth/BoardGame#5]
Przy części operacji na listach (dodawanie lub usuwanie) leci poniższy wyjątek.
Trzeba rozwarzyć jak rozwiązać ten problem.

Exception in thread "LWJGL Application" java.util.ConcurrentModificationException
    at java.util.ArrayList$SubList.checkForComodification(ArrayList.java:1169)
    at java.util.ArrayList$SubList.listIterator(ArrayList.java:1049)
    at java.util.AbstractList.listIterator(AbstractList.java:299)
    at java.util.ArrayList$SubList.iterator(ArrayList.java:1045)
    at java.util.AbstractCollection.contains(AbstractCollection.java:99)
    at java.util.ArrayList.batchRemove(ArrayList.java:700)
    at java.util.ArrayList.removeAll(ArrayList.java:671)
    at pl.agh.edu.boardgame.core.Player.removeNecessaryTokens(Player.java:184)
    at pl.agh.edu.boardgame.core.BoardGameMain.nextTurn(BoardGameMain.java:404)
    at pl.agh.edu.boardgame.adapters.NextTurnButtonAdapter.touchDown(NextTurnButtonAdapter.java:56)
    at com.badlogic.gdx.InputMultiplexer.touchDown(InputMultiplexer.java:90)
    at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:317)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:199)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)

**Comment by DcortezMeleth** [comment]
Chyba udało się poprawić we wcześniejszych commitach.
Nie widziałem tego błędu od dawna.
